apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-multi-zone-c
  namespace: default
  labels:
    app: test-multi-zone-c
    test-type: multi-zone
    zone-test: zone-c
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-multi-zone-c
  template:
    metadata:
      labels:
        app: test-multi-zone-c
        test-type: multi-zone
        zone-test: zone-c
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
