apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-burst-2
  namespace: default
  labels:
    app: test-burst-2
    test-type: burst-test
spec:
  replicas: 15
  selector:
    matchLabels:
      app: test-burst-2
  template:
    metadata:
      labels:
        app: test-burst-2
        test-type: burst-test
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
