apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-tsc-controller-config
  namespace: {{ .Release.Namespace | default "castai-agent" }}
  labels:
    {{- include "castai-tsc-controller.labels" . | nindent 4 }}
data:
  defaultConstraints: '{{ include "castai-tsc-controller.constraintsJson" . }}'
  skipSingleReplica: "{{ .Values.config.skipSingleReplica }}"
  logInterval: "{{ .Values.config.logInterval }}"
  reconcileInterval: "{{ .Values.config.reconcileInterval }}"
  garbageCollectInterval: "{{ .Values.config.garbageCollectInterval }}"
  {{- if .Values.config.exclusions }}
  exclusions: '{{ .Values.config.exclusions | toJson }}'
  {{- else }}
  exclusions: "[]"
  {{- end }}