//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies a TSCOriginal into out.
func (in *TSCOriginal) DeepCopyInto(out *TSCOriginal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of TSCOriginal.
func (in *TSCOriginal) DeepCopy() *TSCOriginal {
	if in == nil {
		return nil
	}
	out := new(TSCOriginal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *TSCOriginal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies a TSCOriginalSpec into out.
func (in *TSCOriginalSpec) DeepCopyInto(out *TSCOriginalSpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.OriginalTSCs != nil {
		in, out := &in.OriginalTSCs, &out.OriginalTSCs
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
}

// DeepCopy returns a deep copy of TSCOriginalSpec.
func (in *TSCOriginalSpec) DeepCopy() *TSCOriginalSpec {
	if in == nil {
		return nil
	}
	out := new(TSCOriginalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a TSCOriginalStatus into out.
func (in *TSCOriginalStatus) DeepCopyInto(out *TSCOriginalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of TSCOriginalStatus.
func (in *TSCOriginalStatus) DeepCopy() *TSCOriginalStatus {
	if in == nil {
		return nil
	}
	out := new(TSCOriginalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a TSCOriginalList into out.
func (in *TSCOriginalList) DeepCopyInto(out *TSCOriginalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TSCOriginal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of TSCOriginalList.
func (in *TSCOriginalList) DeepCopy() *TSCOriginalList {
	if in == nil {
		return nil
	}
	out := new(TSCOriginalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *TSCOriginalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies a TargetRef into out.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
	out.UID = in.UID
}

// DeepCopy returns a deep copy of TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a JVMProbeOriginal into out.
func (in *JVMProbeOriginal) DeepCopyInto(out *JVMProbeOriginal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of JVMProbeOriginal.
func (in *JVMProbeOriginal) DeepCopy() *JVMProbeOriginal {
	if in == nil {
		return nil
	}
	out := new(JVMProbeOriginal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JVMProbeOriginal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies a JVMProbeOriginalSpec into out.
func (in *JVMProbeOriginalSpec) DeepCopyInto(out *JVMProbeOriginalSpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.OriginalContainers != nil {
		in, out := &in.OriginalContainers, &out.OriginalContainers
		*out = make(map[string]ContainerProbes, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
}

// DeepCopy returns a deep copy of JVMProbeOriginalSpec.
func (in *JVMProbeOriginalSpec) DeepCopy() *JVMProbeOriginalSpec {
	if in == nil {
		return nil
	}
	out := new(JVMProbeOriginalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a ContainerProbes into out.
func (in *ContainerProbes) DeepCopyInto(out *ContainerProbes) {
	*out = *in
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of ContainerProbes.
func (in *ContainerProbes) DeepCopy() *ContainerProbes {
	if in == nil {
		return nil
	}
	out := new(ContainerProbes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a JVMProbeOriginalStatus into out.
func (in *JVMProbeOriginalStatus) DeepCopyInto(out *JVMProbeOriginalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of JVMProbeOriginalStatus.
func (in *JVMProbeOriginalStatus) DeepCopy() *JVMProbeOriginalStatus {
	if in == nil {
		return nil
	}
	out := new(JVMProbeOriginalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies a JVMProbeOriginalList into out.
func (in *JVMProbeOriginalList) DeepCopyInto(out *JVMProbeOriginalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JVMProbeOriginal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of JVMProbeOriginalList.
func (in *JVMProbeOriginalList) DeepCopy() *JVMProbeOriginalList {
	if in == nil {
		return nil
	}
	out := new(JVMProbeOriginalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JVMProbeOriginalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
