apiVersion: v2
name: castai-jvm-probe-controller
description: CAST AI JVM Probe Controller - Automatically detects JVM containers and injects health probes
type: application
version: 0.0.3
appVersion: "0.0.3"
keywords:
  - castai
  - kubernetes
  - jvm
  - probe
  - health check
  - spring boot
  - quarkus
  - micronaut
maintainers:
  - name: CAST AI
    email: support@cast.ai
sources:
  - https://github.com/castai/sales-engineering-snaphot-analyzer