apiVersion: v2
name: castai-tsc-controller
description: CAST AI Topology Spread Constraints Controller - Automatically injects TopologySpreadConstraints into Deployments and StatefulSets
type: application
version: 0.2.3
appVersion: "v1.0.0"
keywords:
  - castai
  - kubernetes
  - topology
  - tsc
  - topology spread
maintainers:
  - name: CAST AI
    email: support@cast.ai
sources:
  - https://github.com/castai/sales-engineering-snaphot-analyzer