apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jvm-bulk-3
  namespace: default
  labels:
    app: test-jvm-bulk-3
    test-type: jvm-bulk
spec:
  replicas: 8
  selector:
    matchLabels:
      app: test-jvm-bulk-3
  template:
    metadata:
      labels:
        app: test-jvm-bulk-3
        test-type: jvm-bulk
    spec:
      containers:
        - name: micronaut-app
          image: nginx:alpine
          env:
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: JAVA_HOME
              value: "/usr/lib/jvm/java-17-openjdk"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
