apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-tsc-controller
  namespace: castai-agent
  labels:
    app.kubernetes.io/name: castai-tsc-controller
    app.kubernetes.io/component: tsc-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-tsc-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: castai-tsc-controller
        app.kubernetes.io/component: tsc-controller
    spec:
      serviceAccountName: castai-workload-controllers
      containers:
        - name: tsc-controller
          image: bitnami/kubectl:latest
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-jvm-probe-controller
  namespace: castai-agent
  labels:
    app.kubernetes.io/name: castai-jvm-probe-controller
    app.kubernetes.io/component: jvm-probe-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-jvm-probe-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: castai-jvm-probe-controller
        app.kubernetes.io/component: jvm-probe-controller
    spec:
      serviceAccountName: castai-workload-controllers
      containers:
        - name: jvm-probe-controller
          image: bitnami/kubectl:latest
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
