apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-pdb-controller-config
  namespace: {{ .Release.Namespace | default "castai-agent" }}
  labels:
    {{- include "castai-pdb-controller.labels" . | nindent 4 }}
data:
  defaultMinAvailable: "{{ .Values.config.defaultPDB.minAvailable }}"
  defaultUnhealthyPodEvictionPolicy: "{{ .Values.config.defaultPDB.unhealthyPodEvictionPolicy }}"
  enableForkPattern: "{{ .Values.config.enableForkPattern }}"
  detectPoorPDBs: "{{ .Values.config.detectPoorPDBs }}"
  fixPoorPDBs: "{{ .Values.config.fixPoorPDBs }}"
  skipSingleReplica: "{{ .Values.config.skipSingleReplica }}"
  logInterval: "{{ .Values.config.logInterval }}"
  pdbScanInterval: "{{ .Values.config.pdbScanInterval }}"
  garbageCollectInterval: "{{ .Values.config.garbageCollectInterval }}"
  {{- if .Values.config.exclusions }}
  exclusions: '{{ .Values.config.exclusions | toJson }}'
  {{- else }}
  exclusions: "[]"
  {{- end }}